### ISSUE TITLE
something wrong when I enable gdb

### ISSUE THREAD

**Issue by b33t1e** [nccgroup/asafw#1]
when I follow your step to Configuring a Cisco ASA test environment, the last step trouble me. Something wrong with the gdb inside the firmware. The firmware I use is asav-941-200.qcow2. Please look at the picture
![capture](https://user-images.githubusercontent.com/33768821/36031385-720ecd2e-0d5f-11e8-8f37-7b0cc719fcb5.PNG)
Please Help Me !!!!!

**Comment by saidelike** [comment]
Hi b33t1e,

Some firmware files do not have `gdbserver` already included. It is the case for `asav941-200.qcow2` that you are using as well as `asav981-5.qcow2` that we used in the tutorial you are following.

One thing you are probably missing is that you need to use "--inject-gdb"  as detailed in [1]. The way we have this injection working is by taking one `gdbserver` from another firmware that has already been extracted. At the moment, we use the hardcoded `asa931-smp-k8.bin` [2].

So the following should work:

First, unpack the firmware with gdbserver

```
# unpack_repack_bin.sh -i asa931-smp-k8.bin -u
```

You should now have `_asa931-smp-k8.bin.extracted/rootfs/usr/bin/gdbserver`
Now, unpack/repack firmware by injecting gdbserver from previous firmware

```
# unpack_repack_qcow2.sh -i asav941-200.qcow2 -g --inject-gdb
```

Note that you should be able to use any other `asa*-smp-k8.bin` (smp is required as 64-bit)

[1] https://github.com/nccgroup/asatools/blob/master/tutorial.md#enabling-gdb-in-firmware 
[2] https://github.com/nccgroup/asafw/blob/master/unpack_repack_bin.sh#L524 (inject_gdb())

Hope this helps.

**Comment by b33t1e** [comment]
This really helps!!! Thanks a lot!!!
