### ISSUE TITLE
Hardcoded Python location in bin.py and helper.py

### ISSUE THREAD

**Issue by joe-graham** [nccgroup/asafw#3]
The shebang in the bin.py and helper.py programs uses a hardcoded Python location instead of using env. Switching this over would allow asafw to work on platforms that don't put python3 in /usr/bin, like on macOS.

**Comment by saidelike** [comment]
Thanks Joe, we hadn't tested on OS X. Glad you found a fix. Feel free to send any other PR if you have any other problem.
