### ISSUE TITLE
How to access to the serial-shell after enable it?

### ISSUE THREAD

**Issue by cq674350529** [nccgroup/asafw#9]
Hi, thanks your guys for providing these great tools.
I want to get a shell (not Cisco CLI) on the device emulated by `GNS3`.  As far as I know, there are three ways provided by `asafw` tool to do this.

- using `-r` option
I can access to a shell. But the shell is too early, many pre-works haven't been done. So it's not what I want.
- using `--debugshell` option
When I try to `ssh` to the device, it just crashes instead of giving me a reverse-shell. I haven't debugged it heavily. I'll do it when I'm free.
- using `--serialshell` option
The qemu options are `-cpu Haswell -smp 4,sockets=4,cores=1,threads=1 -serial telnet:127.0.0.1:15002,server,nowait`.
The outputs of device in `vnc` are as follows.
![device output](https://user-images.githubusercontent.com/13868458/50953003-fab97f00-14a9-11e9-836b-2edc5cce5d34.png)

Does it works as expected when using `--serialshell` option? How can I access to the serial shell?

Any advice would be appreciated! Thanks in advance.

**Comment by cq674350529** [comment]
I figured out the cause of device crash when enabling `--debug-shell` in my case. I looked the lina binary with shell injected, a hard-coded address (`socks_proxy_server_start`) was used. But I didn't add the `--disable-aslr` option when repacking the qcow2.
So when enabling `debug-shell`, one need to add both the `--debug-shell` and `--disable-aslr` option.

**Comment by saidelike** [comment]
You are right about everything.

* you need to disable ASLR when using `--debug-shell` as you figured out we don't support resolving `lina` adresses on the fly
* for the serial shell, the option `-serial telnet:127.0.0.1:15002` basically says to forward the serial port inside ASA (QEMU) to the outside world (the host machine) on TCP port 15002. So you can access it with `nc 127.0.0.1 15002`

If everything works for you, feel free to close the issue.

**Comment by cq674350529** [comment]
@saidelike Thanks.

Using `nc 127.0.0.1 15002` works well for me.

As to enabling debugshell with `--debug-shell` option, I have made it work without needing to disable `ASLR`. That is, for some newer images such as `asav9101.qcow2`, which have trouble in disabling `ASLR` at the moment, the debugshell can work well.

I'll create a pull request later.
